### PR TITLE
Update build version as 2.0.3 and also update readme.md.

### PR DESCRIPTION
**Pull request by vsachinv**
Need to publish plugin with new build version as 2.0.2 doesn't contains 3.3.x branch latest changes.

### CODE REVIEW

**Comment by chrisbitmead** [comment]
I hate to comment at an inappropriate place, but where in this project can you comment?

1) This seems to purporting to be the new "official" place for this plugin, but where is the issue tracking???!?!?!?!

2)  the main page of this git repo inks to http://grails.org/plugin/asynchronous-mail which is 404

3) I've been maintaining my own version of this plugin for a while now. I would like to consider submitting some carefully thought out patches to it, if this is going to be its future home. But with the above issues, it feels like still a dead project and I'm tempted to release a competitor.

**Comment by matrei** [comment]
Hi @vsachinv, thanks for your contribution! Repo ownership, maven coordinates and publishing procedure has changed since v2.0.x/3.3.x was last released. To release v2.0.3 these things also need to be addressed/backported to this branch. As Grails 3 is now EOL this has not been done.

If you want you can backport the necessary changes in this pull request and we can release v2.0.3.

**Comment by matrei** [comment]
Hi @chrisbitmead!

1. Thanks for bringing the missing issues tab to my attention! Is seems to be a setting in Github that I do not have access to change in this repo. Maybe @sbglasius has access?
2. Good catch, I have removed that old/faulty link.
3. Interesting, patches are welcome!

**Comment by vsachinv** [comment]
> Hi @vsachinv, thanks for your contribution! Repo ownership, maven coordinates and publishing procedure has changed since v2.0.x/3.3.x was last released. To release v2.0.3 these things also need to be addressed/backported to this branch. As Grails 3 is now EOL this has not been done.
> 
> If you want you can backport the necessary changes in this pull request and we can release v2.0.3.

@matrei Sure. I will do the changes.

**Comment by vsachinv** [comment]
> > Hi @vsachinv, thanks for your contribution! Repo ownership, maven coordinates and publishing procedure has changed since v2.0.x/3.3.x was last released. To release v2.0.3 these things also need to be addressed/backported to this branch. As Grails 3 is now EOL this has not been done.
> > If you want you can backport the necessary changes in this pull request and we can release v2.0.3.
> 
> @matrei Sure. I will do the changes.

@matrei I tried to backport gradle publishing tasks. It looks like io.github.gradle-nexus.publish-plugin is not compliant with gradle 3.5. Let me check if I could upgrade gradle version and get the same working.

**Comment by vsachinv** [comment]
@matrei I have added changes to publish over github packages and get the same using https://jitpack.io/ proxy for dependency use so that whoever using 3.3.x can use the same without any issue as Nexus publish plugin has an issue with gradle 5.x lower versions. 
Also added workflow to get the same published automatically after release tag creation.  Please create release tag as 2.0.3 on branch 3.3.x after merging the code as it will publish and can be used as mentioned
[https://jitpack.io/#gpc/grails-asynchronous-mail/2.0.3 ](url)

**Comment by matrei** [comment]
@vsachinv I did the release but regrettably it failed with:
```sh
* What went wrong:
Execution failed for task ':publishMavenPublicationToGitHubPackagesRepository'.
> Failed to publish publication 'maven' to repository 'GitHubPackages'
   > Failed to deploy artifacts: Could not transfer artifact org.grails.plugins:asynchronous-mail:jar:2.0.3 from/to remote (https://maven.pkg.github.com/gpc/grails-asynchronous-mail): Could not write to resource 'org/grails/plugins/asynchronous-mail/2.0.3/asynchronous-mail-2.0.3.jar'
```

**Comment by vsachinv** [comment]
@matrei Did you try from your local? Looks like it got generated correctly as Github action worked.

**Comment by vsachinv** [comment]
@matrei Checked github actions logs actually it was trying to publish twice at same location. Will correct build publish next time. For now package got published correctly so we can mark this task done. For 2.0.4 change I will correct the duplicate maven publish entry.

**Pull request merged**
